FROM 140427343267.dkr.ecr.us-east-2.amazonaws.com/base:latest

# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME
COPY . /app
WORKDIR /app
COPY . /tmp/
EXPOSE 8080
ENTRYPOINT ["python"]
CMD ["app.py"]